# This builds a custom version of PHP and its extensions

name: cerb-dev

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    volumes:
      - ../_conf/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ../../../apple-touch-icon.png:/usr/share/nginx/html/apple-touch-icon.png:ro
      - ../../../favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ../../../robots.txt:/usr/share/nginx/html/robots.txt:ro
  php-fpm:
    build: .
    depends_on:
      - mysql
    environment:
      CERB_SERVICE_TOKEN: ${CERB_SERVICE_TOKEN:-sk_docker_token}
    volumes:
      - ../../..:/var/www/html:ro
      - ../_conf/cerb.config.php:/var/www/html/framework.config.php:ro
      - storage:/var/www/html/storage
  mysql:
    image: mysql:8.4
    command: >
      --mysql-native-password=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cerb}
      MYSQL_USER: ${MYSQL_USER:-cerb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cr3t}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  storage: