# This builds a custom version of PHP and its extensions

name: cerb-dev

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - backend
    volumes:
      - ../_conf/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ../../../apple-touch-icon.png:/usr/share/nginx/html/apple-touch-icon.png:ro
      - ../../../favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ../../../robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ../../../install/cerb_logo.svg:/usr/share/nginx/html/install/cerb_logo.svg:ro
      - ../../../install/install.css:/usr/share/nginx/html/install/install.css:ro
      - ../../../install/jstz.min.js:/usr/share/nginx/html/install/jstz.min.js:ro
  php-fpm:
    build: .
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ../../..:/var/www/html:ro
      - ../_conf/cerb.config.php:/var/www/html/framework.config.php:ro
      - storage:/var/www/html/storage
  mysql:
    image: mysql:8
    command: >
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cerb}
      MYSQL_USER: ${MYSQL_USER:-cerb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-s3cr3t}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

networks:
  backend:
    ipam:
      config:
        - subnet: 172.16.2.0/24

volumes:
  db:
  storage: