<?php
namespace Cerb\Extensions\AutomationTemplate;

use Cerb\Agent\Pane\Components;
use DAO_Automation;
use DevblocksPlatform;
use Cerb\Extensions\Extension_AutomationTemplate;

// "AI Agent Chat" -- a code-driven CerbUI wizard (host component + tools + filesystems) that GENERATES the
// agent-loop KATA from the author's answers. Targets the interaction.worker.agent trigger (declared in
// plugin.xml).
//
// The location answer no longer generates anything executable. That trigger now contributes its host
// editor's commands as tools at RUNTIME, off `Cerb\Agent\Pane\Components`, so a chat drives whichever editor
// it is opened beside with nothing in its script. What the location still shapes is the SYSTEM PROMPT: the
// orientation an agent in the Icon Builder needs differs from one in the automation editor, and that prose
// stays in the script where an author can read and revise it.
class AgentChat extends Extension_AutomationTemplate {
	const ID = 'cerb.automation.template.ai.agent_chat';

	function hasWizard() : bool {
		return true;
	}

	/**
	 * The wizard asks only what is hard to type: where the chat lives, which tools it may call, and which
	 * volumes it may mount. It does NOT ask for a system prompt or a model.
	 *
	 * The prompt is generated, because it depends on the location -- an agent in the Icon Builder needs
	 * different orientation than one in the automation editor -- and on what actually got mounted. Asking
	 * for it up front would collect text written before either was decided. Prose is also the one part the
	 * author can fix afterwards in the editor with no KATA knowledge, so it is the cheapest thing to
	 * generate and the most expensive thing to ask for. Models come from the default agent model router.
	 */
	function renderWizard() : string {
		$tpl = DevblocksPlatform::services()->template();

		$tpl->assign('components_json', json_encode($this->_componentChoices()));

		// Tools and filesystems are added live via CerbUI.RecordChooser -- there can be dozens of either, so
		// neither is a list we can render up front.
		return $tpl->fetch('devblocks:cerberusweb.core::internal/automation/editor/wizard_agent_chat.tpl');
	}

	function build(array $answers) : array {
		// The loop is generated from the wizard's answers; the policy only ever needs to allow the agent turn
		// (the tools are separate llm.tool automations with their own policies). No `callers:` block -- an
		// absent one allows every caller, and restricting to `agent.pane` would just break a standalone chat.
		$policy_kata = "commands:\n  llm.agent:\n    allow@bool: yes";

		return [
			'extension_id' => $this->getTriggerId(),
			'script' => $this->_generateAgentChatScript($answers),
			'policy_kata' => $policy_kata,
		];
	}

	/**
	 * The host components an agent pane can be mounted on, for the wizard's picker.
	 *
	 * Alphabetized by the label the author reads, not by the catalog's own order -- the catalog groups the
	 * editors together and puts the odd one out last, which is the right order for reading the file and the
	 * wrong one for finding your location in a menu.
	 */
	private function _componentChoices() : array {
		$out = [];

		foreach(Components::getAll() as $key => $component) {
			$out[] = [
				'key' => $key,
				'label' => $component['label'],
				'icon' => $component['icon'],
				'description' => $component['description'],
				// Both families: what the agent gets for picking this location, browser-answered or not.
				'commands' => count($component['commands']) + count($component['server_tools'] ?? []),
			];
		}

		usort($out, fn($a, $b) => strcasecmp($a['label'], $b['label']));

		return $out;
	}

	// Generate the Agent Chat loop KATA from the wizard's answers.
	private function _generateAgentChatScript(array $answers) : string {
		// The chat window title is single-line; strip newlines and fall back to a default.
		$title = trim(preg_replace('/[\r\n]+/', ' ', strval($answers['title'] ?? '')));
		if('' === $title)
			$title = 'Agent Chat';

		$component_key = trim(strval($answers['component'] ?? ''));
		$component = Components::get($component_key);

		// The client posts array/object answers (tools, filesystems) as JSON strings -- decode them.
		$tools_answer = $this->_decodeAnswer($answers['tools'] ?? []);
		$filesystems_answer = $this->_decodeAnswer($answers['filesystems'] ?? []);

		$mounts = $this->_mounts($filesystems_answer);

		$system_prompt = $this->_systemPrompt($component);

		$tools_block = $this->_toolsBlock($tools_answer);

		// `on_tool:` only earns its place when the author picked `llm.tool` automations. A host component's
		// own commands don't need it -- the node emits their browser round-trip itself, and that render is
		// already a repaint -- so generating one for a chat with no picked tools was pure boilerplate.
		$on_tool_block = $tools_answer ? $this->_onToolBlock() : '';

		$skeleton = <<<'KATA'
# An interactive AI agent chat (generated by the Automation Builder). Each turn shows the transcript and a
# prompt, sends your message to the agent (running any tools it calls), and loops.
#
# Models come from the default agent model router, so this runs as-is. To pin them, uncomment the `agent:`
# lines below and name an AI agent -- that stays portable, because the agent record carries the router.
#
__WHERE_TO_ADD__

start:
  set/init:
    prompt_agent@text:
    session_id: {{uuid()}}

  while:
    if@bool: yes
    do:
      # If the user sent a message, run an agent turn (this also runs any tools the agent calls).
      outcome/hasPrompt:
        if@bool: {{prompt_agent}}
        then:
          llm.agent:
            output: results
            inputs:
              # Name an AI agent to pin which models this chat may use. Omitted, the default router
              # decides. (`llm.router:` can name a specific router instead, but its name is local to
              # this environment -- so don't hardcode one in anything you ship.)
              #agent: @your-agent
              session_id@key: session_id
              system_prompt@ref: system_prompt
              messages:
                message:
                  role: user
                  content@key: prompt_agent
                  images@key,optional: prompt_agent__images
              # The built-in `/commands` this agent honors. Opt-in and per-node: nothing is exposed
              # that you didn't ask for.
              commands:
                command/compact:
__MOUNTS__
__TOOLS__
__ON_TOOL__
            on_success:
              set:
                session_id: {{results.session_id}}
            # A failed turn (bad model, provider error, rate limit, timeout) returns to the chat instead
            # of ending the interaction: the composer restores the message that didn't send and shows the
            # reason above it. Branch here on {{results.error_status}}, {{results.retryable}}, and
            # {{results.retry_after}} if you want to handle a class of failure differently. Do NOT use
            # error:/return: here -- that ends the session and loses the transcript.
            on_error:

      # Show the transcript and prompt for the next message.
      await/chat:
        form:
          title: __TITLE__
          elements:
            llmTranscript/prompt_transcript:
              session_id: {{session_id}}
              thinking: raw
              tools: raw
              expand: none
              layout: interleaved
              tokens@bool: yes
            agentPrompt/prompt_agent:
              placeholder: Message the agent...
              session_id: {{session_id}}
              required@bool: yes
              #agent: @your-agent
              # What the composer OFFERS -- deliberately separate from the `commands:`/`mounts:` above,
              # which are what the agent ACTS on.
              commands:
                compact:
                rewrite/flatten:
                  description: Aggressively compact the thread
                  text@text: /compact hard
              # What `@` autocompletes. Opt-in: without this block `@` completes nothing.
              references:
                workers:
__REFERENCES__
            submit:
              continue@bool: no
              reset@bool: no

&transcript_summary:
  session_id: {{session_id}}
  thinking: summary
  tools: summary

&system_prompt@text:
__SYSTEM_PROMPT__

KATA;

		// Every chat goes on the `agent.pane` toolbar, the command bar included -- its menu merges that toolbar's
		// `commandbar` items with `global.menu`'s own. What differs is the GATE: an item with no `hidden@bool:`
		// appears on every pane and in the command bar, which is rarely what a chat written for one editor
		// wants, so the generated comment spells out the gate for the location that was picked.
		$where_to_add = "# To offer this chat, add it to the `agent.pane` toolbar in Setup. That toolbar ships with no items,\n"
			. "# so a freshly saved chat isn't reachable until you do.";

		if($component_key)
			$where_to_add .= sprintf(
				"\n#\n# Without a gate it appears everywhere an agent pane does. To keep it to %s, give the toolbar item:\n"
					. "#   hidden@bool: {{ component != '%s' }}",
				$component['label'] ?? $component_key,
				$component_key
			);

		$replacements = [
			'__WHERE_TO_ADD__' => $where_to_add,
			'__TITLE__' => $title,
			"__MOUNTS__\n" => $this->_indent($mounts['mounts'], 14),
			"__TOOLS__\n" => $tools_block,
			"__ON_TOOL__\n" => $on_tool_block,
			"__REFERENCES__\n" => $this->_indent($mounts['references'], 16),
			"__SYSTEM_PROMPT__\n" => $this->_indent($system_prompt, 2),
		];

		return str_replace(array_keys($replacements), array_values($replacements), $skeleton);
	}

	/**
	 * Indent every non-empty line of a block by $spaces, and guarantee a trailing newline when there's
	 * content. Every generated block goes through this, so each nesting depth is stated once as a number
	 * rather than baked into the leading whitespace of a dozen string literals -- which is what made the
	 * previous generator's system-prompt splice break silently if the skeleton was ever re-indented.
	 *
	 * Blocks are built at depth 0 and indented on the way out, so they nest by composition: an inner
	 * _indent() call is relative to its parent, not absolute.
	 */
	private function _indent(string $block, int $spaces) : string {
		if('' === ($block = rtrim($block, "\n")))
			return '';

		$pad = str_repeat(' ', $spaces);
		$out = '';

		foreach(preg_split('/\r?\n/', $block) as $line)
			$out .= ('' === trim($line)) ? "\n" : ($pad . $line . "\n");

		return $out;
	}

	// The client stringifies array/object answers as JSON; accept either shape.
	private function _decodeAnswer($answer) : array {
		if(is_string($answer))
			$answer = json_decode($answer, true);

		return is_array($answer) ? $answer : [];
	}

	/**
	 * The whole system prompt, generated: the location's own instructions, then the tool inventory that
	 * location gives it.
	 *
	 * Generated rather than asked for because both parts depend on an answer given LATER in the same wizard --
	 * the location supplies the opening AND the inventory. It is also the one section the author can revise
	 * afterwards by typing into the automation editor, which is why it's the right thing to hand them finished
	 * rather than blank.
	 *
	 * The tool inventory is spelled out even though the provider already sends tool schemas: a model that
	 * isn't told in prose that it can read the editor tends to ask the user to paste instead. That reasoning
	 * is specific to the EDITOR tools, whose schemas are one line each -- it does not extend to the terminal,
	 * whose schema is exhaustive (see the note at the end of this method).
	 */
	private function _systemPrompt(?array $component) : string {
		$system_prompt = $component
			? trim(strval($component['instructions'] ?? ''))
			: '';

		if('' === $system_prompt)
			$system_prompt = 'You are a helpful AI agent.';

		$lines = [];

		// Both families, since the model can't tell them apart and shouldn't have to: `commands` are answered by
		// the browser, `server_tools` here. A component may have neither -- the command bar is a real place
		// whose host has no command bridge yet -- and then there is no inventory to write. Saying "you act
		// through these tools:" above an empty list, and then telling it to make changes, would contradict
		// instructions that just said it can't see the screen.
		$tools = [];

		if($component) {
			// Bridge commands carry their model-facing name in `tool`; a server tool IS its key.
			foreach($component['commands'] as $command)
				$tools[$command['tool']] = $command['description'];

			foreach($component['server_tools'] ?? [] as $tool_name => $server_tool)
				$tools[$tool_name] = $server_tool['description'];
		}

		if($tools) {
			// The instructions above already say where the agent is; this just names the tools.
			$lines[] = '';
			$lines[] = 'You act on it through these tools:';

			foreach($tools as $tool_name => $description)
				$lines[] = sprintf('- %s -- %s', $tool_name, $description);

			$lines[] = '';
			$lines[] = 'Read before you write. Prefer acting over describing: make the change, then say briefly what changed and why.';
		}

		// NOTHING about the filesystem is written here. The `agent_terminal` tool's own schema description
		// already carries all of it, and carries it better: a "Mounted filesystems:" overview with each
		// volume's path, mode, description AND an `ls` of its contents, the whole-line-in-`command` shape, "no
		// working directory -- use absolute paths or @<filesystem>/path", `Filesystem::help()` verbatim, and
		// `/tmp` plus the `|` pipeline. Restating it cost a copy of all that in every turn's system prompt.
		//
		// It was also WRONG in a way it couldn't detect: it listed `search` unconditionally, while the schema
		// drops `search` when no volumes are mounted (it needs a fulltext index only a volume has). So a
		// /tmp-only agent was told about a command it doesn't have.

		return $system_prompt . "\n" . implode("\n", $lines);
	}

	/**
	 * The `mounts:` block (what the agent can actually read/write) and the matching `references: filesystems:`
	 * block (what `@` completes for the human). Same answer, two blocks: they're decoupled on purpose, so a
	 * volume can be mounted without cluttering the composer's autocomplete, or offered without being mounted.
	 *
	 * `mounts:` is ALWAYS emitted, even with nothing selected. Writing the key at all is what enables the
	 * filesystem (LlmAgentNode::_isFilesystemEnabled tests the KEY, not its value), and an empty block means
	 * `/tmp` only -- a read-write scratch area plus the `|` Twig pipeline, which is the difference between an
	 * agent that can count and filter its own output and one that has to eyeball it. Cheap, and nothing is
	 * exposed: `/tmp` is per-session and holds only what the agent puts there.
	 *
	 * @return array{mounts:string, references:string}
	 */
	private function _mounts(array $filesystems) : array {
		$mounts = '';
		$references = '';

		foreach($filesystems as $filesystem) {
			if(!is_array($filesystem))
				continue;

			if('' === ($name = trim(strval($filesystem['name'] ?? ''))))
				continue;

			$mounts .= $name . ":\n";

			// Read-only is the default, so only say so when it isn't. The wizard's switcher speaks `ro`/`rw`
			// (matching the filesystem terminal); the generated KATA spells it out, since both are accepted
			// and the long form is the one an author reads correctly without checking.
			if(in_array(strtolower(trim(strval($filesystem['mode'] ?? ''))), ['rw', 'read-write', 'readwrite'], true))
				$mounts .= "  mode: read-write\n";

			$references .= $name . ":\n";
		}

		// Nothing selected: keep the key, lose the children. The comment goes in the generated script because
		// an apparently-empty block is exactly the kind of thing an author tidies away, and deleting it takes
		// the agent's whole filesystem with it -- silently, since the tool simply stops being offered.
		if('' === $mounts)
			return [
				'mounts' => "# An empty `mounts:` still enables the filesystem, mounting only a read-write\n"
					. "# `/tmp`. Delete this key and the agent loses `agent_terminal` entirely; add volumes\n"
					. "# under it (`<volume>:`, plus `mode: read-write` to allow writes) to mount more.\n"
					. "mounts:\n",
				'references' => '',
			];

		// `/tmp` rides along read-write alongside whatever else is declared; it doesn't need declaring here.
		return [
			'mounts' => "mounts:\n" . $this->_indent($mounts, 2),
			'references' => "filesystems:\n" . $this->_indent($references, 2),
		];
	}

	/**
	 * The `tools:` block: the `llm.tool` automations the author picked, as `automation/` entries.
	 *
	 * The host editor's own commands are NOT here. They're contributed by the trigger at runtime
	 * (`AutomationTrigger_InteractionWorkerAgent::getLlmAgentTools()`, off `Cerb\Agent\Pane\Components`),
	 * the same way `mounts:` provisions `agent_terminal`. Generating them was a tool definition and an await
	 * element per command -- for the automation editor, sixteen blocks of boilerplate in every chat -- that
	 * went stale the moment a host gained a command and that nobody could safely edit.
	 */
	private function _toolsBlock(array $tools_answer) : string {
		if('' === ($block = $this->_automationToolsBlock($tools_answer)))
			return '';

		return $this->_indent("tools:\n" . $this->_indent($block, 2), 14);
	}

	/**
	 * The author's picked `llm.tool` automations. Each answer is { id, alias, label_summary, label_active }.
	 * Resolve id -> automation name for the uri; key by the author's readable alias (default = the name) so
	 * the model sees `docs_search`, not `tool123`, and carry the transcript labels.
	 */
	private function _automationToolsBlock(array $tools_answer) : string {
		$tools_by_id = [];

		foreach($tools_answer as $tool) {
			if(!is_array($tool))
				continue;

			if(($id = intval($tool['id'] ?? 0)))
				$tools_by_id[$id] = $tool;
		}

		if(!$tools_by_id)
			return '';

		$block = '';
		$automations = DAO_Automation::getIds(array_keys($tools_by_id));

		foreach($tools_by_id as $id => $tool) {
			if(!isset($automations[$id]))
				continue;

			$name = $automations[$id]->name;
			$alias = $this->_toolAlias(strval($tool['alias'] ?? '')) ?: $this->_toolAlias($name);

			$block .= sprintf("automation/%s:\n", $alias);
			$block .= sprintf("  uri: cerb:automation:%s\n", $name);

			$active = trim(strval($tool['label_active'] ?? ''));
			$summary = trim(strval($tool['label_summary'] ?? ''));

			if('' === $active && '' === $summary)
				continue;

			$block .= "  labels:\n";

			if('' !== $active)
				$block .= sprintf("    active: %s\n", $active);

			if('' !== $summary)
				$block .= sprintf("    summary: %s\n", $summary);
		}

		return $block;
	}

	/**
	 * The `on_tool:` branch: repaint the transcript between tool calls, then continue.
	 *
	 * It runs BEFORE any tool that has to reach the browser, which is what makes it the place to put an
	 * approval step -- render a confirmation here and answer with `tool.return:` to refuse, and the editor is
	 * never touched. It also lets a turn BREATHE: an agent firing five commands would otherwise do it all in
	 * one request and hit the time limit.
	 *
	 * No `tool.return:` in the generated form. The tool's own result stands -- returning here would overwrite
	 * it with an empty string.
	 */
	private function _onToolBlock() : string {
		$block = "on_tool:\n"
			. "  # Runs before every tool call, including the editor commands this chat's location provides.\n"
			. "  # Repaints the transcript so a long tool run shows progress. To gate a tool behind a human,\n"
			. "  # branch on {{__tool.name}} here and answer with `tool.return:` -- an answered call never\n"
			. "  # reaches the editor.\n"
			. "  await:\n"
			. "    form:\n"
			. "      elements:\n"
			. "        llmTranscript/prompt_transcript@ref: transcript_summary\n"
			. "        submit:\n"
			. "          is_automatic@bool: yes\n";

		return $this->_indent($block, 12);
	}

	// A readable, KATA-safe alias (function name the model sees): lowercase, non-word -> underscore.
	private function _toolAlias(string $name) : string {
		$alias = trim(preg_replace('/[^a-z0-9_]+/', '_', strtolower($name)), '_');
		return $alias ?: 'tool';
	}
}
