<?php
namespace Cerb\Extensions\AutomationTemplate;

use DevblocksPlatform;
use Cerb\Extensions\Extension_AutomationTemplate;

// "Worker Interaction" — a simple, LINEAR worker interaction (no chat loop): show a form, then a result. The
// wizard customizes the common bits (title, the prompt + its answer type, the result message); build() drops a
// `# [TODO]` where the author acts on the submitted value. Targets the interaction.worker trigger.
class WorkerInteraction extends Extension_AutomationTemplate {
	const ID = 'cerb.automation.template.interactions.worker';

	function hasWizard() : bool {
		return true;
	}

	function renderWizard() : string {
		$tpl = DevblocksPlatform::services()->template();
		return $tpl->fetch('devblocks:cerberusweb.core::internal/automation/editor/wizard_worker_interaction.tpl');
	}

	function build(array $answers) : array {
		return [
			'extension_id' => $this->getTriggerId(),
			'script' => $this->_generateScript($answers),
			'policy_kata' => "commands:\n  # [TODO] Add a command policy for any privileged commands you use (record.*, mail.*, http.request, …).",
		];
	}

	private function _generateScript(array $answers) : string {
		// Title + prompt label are single-line; strip newlines and fall back to sensible defaults.
		$title = trim(preg_replace('/[\r\n]+/', ' ', strval($answers['title'] ?? '')));
		if('' === $title)
			$title = 'Worker Interaction';
		$prompt = trim(preg_replace('/[\r\n]+/', ' ', strval($answers['prompt'] ?? '')));
		if('' === $prompt)
			$prompt = 'What would you like to do?';

		// Answer type = a text or textarea await-form element.
		$type = ('textarea' === ($answers['answer_type'] ?? 'text')) ? 'textarea' : 'text';

		// Result message (may be multi-line, and may reference {{prompt_input}}); indent under content@text:.
		$result = trim(strval($answers['result'] ?? ''));
		if('' === $result)
			$result = 'Thanks!';
		$result_block = '';
		foreach(preg_split('/\r?\n/', $result) as $line)
			$result_block .= '            ' . $line . "\n";

		// Title/label are single-line (newlines stripped) so they inline safely; the multi-line result rides a
		// content@text: block.
		$skeleton = <<<'KATA'
# A simple, linear worker interaction (generated by the Automation Builder): it shows a form, then a result.

start:
  await/prompt:
    form:
      title: __TITLE__
      elements:
        __TYPE__/prompt_input:
          label: __LABEL__
          required@bool: yes
        submit:
          continue@bool: yes

  # [TODO] Do something with the submitted value ({{prompt_input}}).

  await/result:
    form:
      elements:
        say/result:
          content@text:
__RESULT__
KATA;

		$script = str_replace('__TITLE__', $title, $skeleton);
		$script = str_replace('__LABEL__', $prompt, $script);
		$script = str_replace('__TYPE__', $type, $script);
		// __RESULT__ is the nowdoc's last line (no trailing newline); $result_block supplies its own.
		$script = str_replace('__RESULT__', rtrim($result_block, "\n"), $script);

		return $script;
	}
}
